### ISSUE TITLE
[Bug]: unused parameters in  m3gnet

### ISSUE THREAD

**Issue by JonathanSchmidt1** [IntelLabs/matsciml#137]
### Expected behavior

I would expect the model not to have any unused parameters during the backward process.

### Actual behavior

Running ddp without strategy find_unused_parameters crashes.
My theory is that 
```
class M3GNet(AbstractDGLModel):
    def __init__(
        self, element_types: list[str], return_all_layer_output: bool, *args, **kwargs
    ):
        super().__init__(atom_embedding_dim=len(element_types))
        self.elemenet_types = element_types
        self.all_embeddings = return_all_layer_output
        self.model = matgl_m3gnet(element_types, *args, **kwargs)
        self.atomic_embedding = self.model.embedding
```
self.atomic_embedding should be self.atom_embedding as that is the name in the AbstractDglTask.
As the m3gnet embedding block is more than just node embeddings it should probably just be:
`        self.atom_embedding = self.model.embedding.layer_node_embedding`
This fixed it for me (I also removed the final m3gnet layer so maybe that also has to be done).

### Steps to reproduce the problem

Run m3gnet with ddp.

### Specifications

the latest matsciml version with dgl 1.1.3

**Comment by laserkelvin** [comment]
Thanks @JonathanSchmidt1 - do you want to open a PR with the fix? Otherwise I can

**Comment by JonathanSchmidt1** [comment]
please go ahead :)
