### ISSUE TITLE
Migrate to pyproject.toml

### ISSUE THREAD

**Issue by laserkelvin** [IntelLabs/matsciml#18]
Currently, we used both `setup.py` and `setup.cfg` jointly to overcome some backwards compatibility issues for older versions of `setuptools`. The better practice is to use `pyproject.toml` which is now supported in newer versions of `setuptools`, which provides a more comprehensive packaging and developer experience, as we're able to define formatter configurations, dependencies, and build tools in the same file.

**Comment by Marsh-sudo** [comment]
Would like to help you out with this issue

**Comment by laserkelvin** [comment]
Completed as part of the `v1.0.0` release.
