### ISSUE TITLE
[Bug]: SAM callback does not work for `ForceRegressionTask`

### ISSUE THREAD

**Issue by laserkelvin** [IntelLabs/matsciml#181]
### Expected behavior

Callbacks should be compatible with task abstractions.

### Actual behavior

The `pytest` output:

```console
/home/kinlongk/miniforge3/envs/matsciml-pymatgen-upgrade/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py:208: in _call_callback_hooks
    fn(trainer, trainer.lightning_module, *args, **kwargs)
../callbacks.py:764: in on_before_optimizer_step
    step_output = pl_module.training_step(self.batch, self.batch_idx)
../../models/base.py:1735: in training_step
    opt.step()
/home/kinlongk/miniforge3/envs/matsciml-pymatgen-upgrade/lib/python3.9/site-packages/pytorch_lightning/core/optimizer.py:152: in step
    step_output = self._strategy.optimizer_step(self._optimizer, closure, **kwargs)
E   RecursionError: maximum recursion depth exceeded in comparison
!!! Recursion detected (same locals & position)
```

At face value, it seems that the interaction between `pl_module.training_step` and callbacks result in recursion.

### Steps to reproduce the problem

Run `pytest matsciml/lightning/tests/test_sam.py`

### Specifications

N/A

**Comment by melo-gonzo** [comment]
Just making not that this is the same issue seen when the task pipeline has multiple optimizers.

**Comment by laserkelvin** [comment]
One solution would be to not have the callback use `training_step`, but instead run `_compute_losses` - I'll try that and if it works I'll submit a PR
