### ISSUE TITLE
[Feature request]: Run pre-commit on entire package to ensure consistent formatting

### ISSUE THREAD

**Issue by melo-gonzo** [IntelLabs/matsciml#71]
### Feature/behavior summary

Run the pre-commit hooks on every file in one big PR so future PR's dont flood the change log with formatting updates.

### Request attributes

- [X] Would this be a refactor of existing code?
- [ ] Does this proposal require new package dependencies?
- [ ] Would this change break backwards compatibility?
- [ ] Does this proposal include a new model?
- [ ] Does this proposal include a new dataset?
- [ ] Does this proposal include a new task/workflow?

### Solution description

Run pre-commit hooks on all files.

**Comment by laserkelvin** [comment]
Addressed in #90.
